# Generated by Django 4.2.3 on 2023-08-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non Fiction'), ('Si-Fi', 'Si-Fi'), ('Horor', 'Horor'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('History', 'History'), ('Biography', 'Biography'), ('Cookbook', 'Cookbook'), ('Traveler', 'Traveler')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField()),
            ],
        ),
    ]
